-- ITS Integration 独立应用内嵌库表结构（与 system-manage 无关联）

CREATE TABLE IF NOT EXISTS IT_CONNECTOR_CLIENT (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE3RD         VARCHAR(64)  NOT NULL,
    SCOPE           VARCHAR(64)  NOT NULL DEFAULT '*',
    NAME3RD         VARCHAR(128),
    HOST3RD         VARCHAR(512),
    PROTOCOL        VARCHAR(16)  DEFAULT 'HTTP',
    APP_ID          VARCHAR(256),
    APP_SECRET      VARCHAR(512),
    PUBLIC_KEY      VARCHAR(512),
    PROXY           VARCHAR(128),
    PARAM_JSON      CLOB,
    STATUS          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_IT_CONNECTOR_CLIENT UNIQUE (CODE3RD, SCOPE)
);

CREATE TABLE IF NOT EXISTS IT_CONNECTOR_SPEC (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID       BIGINT       NOT NULL,
    VERSION         VARCHAR(32)  NOT NULL DEFAULT '1.0.0',
    SPEC_JSON       CLOB         NOT NULL,
    AUTH_PROFILE    VARCHAR(64),
    PUBLISH_STATUS  VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    PUBLISHED_AT    TIMESTAMP,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_IT_SPEC_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES IT_CONNECTOR_CLIENT(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_IT_SPEC_CLIENT ON IT_CONNECTOR_SPEC (CLIENT_ID);
CREATE INDEX IF NOT EXISTS IDX_IT_SPEC_PUBLISH ON IT_CONNECTOR_SPEC (PUBLISH_STATUS);
