-- ITS Integration: Connector Spec 表（草案，并入 system-manage 迁移前请评审）
-- 详见 docs/CONNECTOR-PERSISTENCE.md

CREATE TABLE IF NOT EXISTS IT_CONNECTOR_SPEC (
  ID              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID       VARCHAR(20)  NULL COMMENT '租户',
  CLIENT_ID       BIGINT       NOT NULL COMMENT 'SM_THIRDPART_CLIENT.ID',
  CODE3RD         VARCHAR(50)  NOT NULL COMMENT '冗余，便于查询',
  SCOPE           VARCHAR(20)  NULL COMMENT '区域',
  SPEC_VERSION    VARCHAR(20)  NOT NULL DEFAULT '1.0.0' COMMENT 'SemVer',
  SPEC_STATUS     VARCHAR(10)  NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT|PUBLISHED|ARCHIVED',
  AUTH_SUMMARY    VARCHAR(80)  NULL COMMENT '主 Profile 摘要',
  SPEC_JSON       MEDIUMTEXT   NOT NULL COMMENT 'ConnectorSpec JSON',
  CHECKSUM        VARCHAR(64)  NULL COMMENT 'SHA-256',
  PUBLISHED_TIME  DATETIME     NULL,
  CREATE_TIME     DATETIME     NULL,
  UPDATE_TIME     DATETIME     NULL,
  REMARK          VARCHAR(500) NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_CLIENT_VERSION (CLIENT_ID, SPEC_VERSION),
  KEY IDX_CODE3RD_SCOPE (CODE3RD, SCOPE),
  KEY IDX_STATUS (SPEC_STATUS)
) ENGINE=InnoDB COMMENT='第三方 Connector 规格';
